# Generated by Django 4.1.6 on 2023-02-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
