# Generated by Django 4.1.5 on 2023-01-31 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0026_alter_patient_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_rays', to='api.doctor')),
                ('nurse', models.ManyToManyField(related_name='nurse_rays', to='api.nurse')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_rays', to='api.patient')),
            ],
        ),
    ]
